### PR TITLE
add `@onInit` action

### PR DESCRIPTION
**Pull request by miguelcobain**
This action is essentially an "escape hatch" for the caller to be able to access the underlying chart instance.

This is useful for making some advanced customizations, especially important now that chartist is becoming more and more abandoned.

My specific use case is to be able to call `chart.update()` before printing. More info [here](https://github.com/gionkunz/chartist-js/issues/118#issuecomment-72272912).

Does does not involve any breaking changes at all.

### CODE REVIEW

**Review by jherdman — APPROVED** [review]

**Comment by jherdman** [comment]
Looks good! Many thanks! I'll release ASAP.

**Comment by jherdman** [comment]
One last request. Can you rebase this PR on master? I had to do some work to get CI working again.

**Comment by miguelcobain** [comment]
@jherdman I merged master.

**Comment by jherdman** [comment]
Thank you for your contribution, and the kick in the butt to get some maintenance done on this package.

**Comment by jherdman** [comment]
FYI released in 3.1.0.

**Pull request merged**
